### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/Halbis#1]

**Comment by werthen** [comment]
Be useless

**Comment by rien** [comment]
This was the wannabe successor of Haldis. I think this can be thrown away.

**Comment by redfast00** [comment]
Maybe archive it in the Github settings instead of deleting it?

**Comment by werthen** [comment]
It's really not useful to keep this repo at all, iepoev only generated an ew rails models and that's it

**Comment by redfast00** [comment]
Okay, let's remove it then.
